version: "3.8"

name: analytics-mesh

services:
  analytics-mesh:
    image: analytics-mesh:latest
    build: .
    network_mode: "host"
    volumes:
      - .:/opt/analytics-mesh/data/
    init: true
